version: '2'
services:

  pose_laura:
    image: pose_laura:latest
    environment:
      - "DAT_VARIABLE=dat_value"
    volumes:
      - /home/caleml/:/workspace
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidia1:/dev/nvidia1
      - /dev/nvidia2:/dev/nvidia2
      - /dev/nvidia3:/dev/nvidia3
      - /dev/nvidiactl
      - /dev/nvidia-uvm
    ports:
      - 3000:8888
    