version: '3.3'
services:

  dummy:
    image: dummy:latest
    environment:
      - "DAT_VARIABLE=value"
    volumes:
      - /home/{$USER}:/workspace
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
    ports:
      - 3000:3000
    networks:
      overlay: null
    